package com.example.accessingdatamysql.controller;

import com.example.accessingdatamysql.entity.Course;
import com.example.accessingdatamysql.entity.Teacher;
import com.example.accessingdatamysql.repository.CourseRepository;
import com.example.accessingdatamysql.repository.TeacherRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import static java.lang.System.out;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/course") // This means URL's start with /demo (after Application path)
public class CourseController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CourseRepository courseRepository;

    @CrossOrigin(origins = "http://localhost:8082")
    @PostMapping(path = "/all")
    public @ResponseBody String getAllCourse() {
        Iterable<Course> result = courseRepository.findAll();
        StringBuilder response = new StringBuilder();
        response.append('[');
        for (Course course : result) {
            response.append(course.toString()).append(", ");
        }
        if (!response.isEmpty()) {
            response.setLength(response.length() - 2);
        }
        response.append(']');
        out.println(response.toString());
        return response.toString();
    }

    @CrossOrigin(origins = "http://localhost:8082")
    @PostMapping(path = "/addcourse")
    public @ResponseBody String addCourse(String courseid, String coursename) {
        Course course = new Course();
        course.setCourseId(courseid);
        course.setCourseName(coursename);
        courseRepository.save(course);
        return "saved";
    }

    @CrossOrigin(origins = "http://localhost:8082")
    @PostMapping(path = "/deletecourse")
    public @ResponseBody String deleteCourse(String courseid) {
        courseRepository.deleteById(courseid);
        return "deleted";
    }
}
