package com.example.accessingdatamysql.controller;

import com.example.accessingdatamysql.entity.Student;
import com.example.accessingdatamysql.entity.Teacher;
import com.example.accessingdatamysql.repository.TeacherRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import static java.lang.System.out;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/teacher") // This means URL's start with /demo (after Application path)
public class TeacherController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private TeacherRepository teacherRepository;

	@CrossOrigin(origins = "http://localhost:8082")
	@PostMapping(path = "/findteacherid")
	public @ResponseBody String findStudentByUserId(@RequestParam String userid) {
		out.println("查询教师"+userid);
		Iterable<Teacher> result = teacherRepository.getByUserid(userid);
		StringBuilder response = new StringBuilder();
		for (Teacher teacher : result) {
			response.append(teacher.toString()).append(", ");
		}
		if (!response.isEmpty()) {
			response.setLength(response.length() - 2);
		}
		out.println("查询教师"+response.toString());
		return response.toString();
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Teacher> getAllTeacher() {
		// This returns a JSON or XML with the users
		return teacherRepository.findAll();
	}
}
